### ISSUE TITLE
asking for your help

### ISSUE THREAD

**Issue by yangduokmust** [cdiazbas/denoiser#2]
Dear Díaz,

 I want to ask some questions about your article "Solar image denoising with convolutional neural networks".

1. Can you provide a version of the toolkit you are using when you are doing the experiment? For example, python, tensorflow, keras, etc. I found some of the code you provided on github and it always went wrong.
2. In profilePrediction.py, I ran this program, it prompts me No module named 'lptools', I have not found this lptools' after searching the entire Internet. Can you provide me with the complete source code for all the experiments in this article?
3. On the other hand, I am going to start with your experiment and do other solar image denoising experiments. I hope that you can get the complete experimental code, including training, testing and other complete source code. Thank you.
My e-mail is : yangduovie@stu.kust.edu.cn  ,or ,  yangduokmust@gmail.com . I am looking forward to receive your letter.Thanks!

**Comment by cdiazbas** [comment]
Hello,
1 - You are right, I have noticed that the version that is on github does not work with the new version of keras (thanks to @Goobley). I have updated the script to take this into account.
2 - In profilePrediction.py I have a module called lptools. That's true, to read a special type of files. In case you have fits you can use astropy to read fits. (I have also added this library). The script does not include examples, it is just a loop for all the wavelength points.
3 - I am not sure about the data sharing policy in my institute, but you can do the same experiments with your own data or from other datasets. I was showing in the article one application of the method (something that is also available in other places (https://github.com/NVlabs/noise2noise). Do you plan to do the same with data from the same or other telescope? You can also take a public simulation and sinthesize the Stokes profiles.
Regards,
Carlos
